/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.1.2.0 (NJsonSchema v10.0.24.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

export interface IClient {
    GetTaskGroups(): Promise<TaskGroupViewModel[]>;
    PostTaskGroup(taskGroup: TaskGroupDTO): Promise<TaskGroupViewModel>;
    GetTaskGroup(id: number): Promise<TaskGroupViewModel>;
    PatchTaskGroup(id: number, taskGroupUpdate: TaskGroupDTO): Promise<TaskGroupViewModel>;
    DeleteTaskGroup(id: number): Promise<boolean | null>;
    GetUsers(): Promise<UserViewModel[]>;
    GetTaskGroupUserTasks(taskGroupId: number | undefined): Promise<UserTaskViewModel[]>;
    PostUserTask(userTask: UserTaskDTO): Promise<UserTaskViewModel>;
    GetUserTask(id: number): Promise<UserTaskViewModel>;
    PatchUserTask(id: number, userTaskUpdate: UserTaskDTO): Promise<UserTaskViewModel>;
    DeleteUserTask(id: number): Promise<boolean | null>;
}

export class ApiClient implements IClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : <any>window;
        this.baseUrl = baseUrl ? baseUrl : "https://localhost:5001";
    }

    GetTaskGroups(): Promise<TaskGroupViewModel[]> {
        let url_ = this.baseUrl + "/api/TaskGroup";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTaskGroup_GetTaskGroups(_response);
        });
    }

    protected processTaskGroup_GetTaskGroups(response: Response): Promise<TaskGroupViewModel[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <TaskGroupViewModel[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TaskGroupViewModel[]>(<any>null);
    }

    PostTaskGroup(taskGroup: TaskGroupDTO): Promise<TaskGroupViewModel> {
        let url_ = this.baseUrl + "/api/TaskGroup";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(taskGroup);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTaskGroup_PostTaskGroup(_response);
        });
    }

    protected processTaskGroup_PostTaskGroup(response: Response): Promise<TaskGroupViewModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <TaskGroupViewModel>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TaskGroupViewModel>(<any>null);
    }

    GetTaskGroup(id: number): Promise<TaskGroupViewModel> {
        let url_ = this.baseUrl + "/api/TaskGroup/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTaskGroup_GetTaskGroup(_response);
        });
    }

    protected processTaskGroup_GetTaskGroup(response: Response): Promise<TaskGroupViewModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <TaskGroupViewModel>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TaskGroupViewModel>(<any>null);
    }

    PatchTaskGroup(id: number, taskGroupUpdate: TaskGroupDTO): Promise<TaskGroupViewModel> {
        let url_ = this.baseUrl + "/api/TaskGroup/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(taskGroupUpdate);

        let options_ = <RequestInit>{
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTaskGroup_PatchTaskGroup(_response);
        });
    }

    protected processTaskGroup_PatchTaskGroup(response: Response): Promise<TaskGroupViewModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <TaskGroupViewModel>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TaskGroupViewModel>(<any>null);
    }

    DeleteTaskGroup(id: number): Promise<boolean | null> {
        let url_ = this.baseUrl + "/api/TaskGroup/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "DELETE",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTaskGroup_DeleteTaskGroup(_response);
        });
    }

    protected processTaskGroup_DeleteTaskGroup(response: Response): Promise<boolean | null> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            return Promise.resolve(response.ok);
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<null>(<any>null);
    }

    GetUsers(): Promise<UserViewModel[]> {
        let url_ = this.baseUrl + "/api/User";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUser_GetUsers(_response);
        });
    }

    protected processUser_GetUsers(response: Response): Promise<UserViewModel[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <UserViewModel[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserViewModel[]>(<any>null);
    }

    GetTaskGroupUserTasks(taskGroupId: number | undefined): Promise<UserTaskViewModel[]> {
        let url_ = this.baseUrl + "/api/UserTask?";
        if (taskGroupId === null)
            throw new Error("The parameter 'taskGroupId' cannot be null.");
        else if (taskGroupId !== undefined)
            url_ += "taskGroupId=" + encodeURIComponent("" + taskGroupId) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUserTask_GetTaskGroupUserTasks(_response);
        });
    }

    protected processUserTask_GetTaskGroupUserTasks(response: Response): Promise<UserTaskViewModel[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <UserTaskViewModel[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserTaskViewModel[]>(<any>null);
    }

    PostUserTask(userTask: UserTaskDTO): Promise<UserTaskViewModel> {
        let url_ = this.baseUrl + "/api/UserTask";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(userTask);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUserTask_PostUserTask(_response);
        });
    }

    protected processUserTask_PostUserTask(response: Response): Promise<UserTaskViewModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <UserTaskViewModel>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserTaskViewModel>(<any>null);
    }

    GetUserTask(id: number): Promise<UserTaskViewModel> {
        let url_ = this.baseUrl + "/api/UserTask/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUserTask_GetUserTask(_response);
        });
    }

    protected processUserTask_GetUserTask(response: Response): Promise<UserTaskViewModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <UserTaskViewModel>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserTaskViewModel>(<any>null);
    }

    PatchUserTask(id: number, userTaskUpdate: UserTaskDTO): Promise<UserTaskViewModel> {
        let url_ = this.baseUrl + "/api/UserTask/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(userTaskUpdate);

        let options_ = <RequestInit>{
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUserTask_PatchUserTask(_response);
        });
    }

    protected processUserTask_PatchUserTask(response: Response): Promise<UserTaskViewModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <UserTaskViewModel>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserTaskViewModel>(<any>null);
    }

    DeleteUserTask(id: number): Promise<boolean | null> {
        let url_ = this.baseUrl + "/api/UserTask/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "DELETE",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUserTask_DeleteUserTask(_response);
        });
    }

    protected processUserTask_DeleteUserTask(response: Response): Promise<boolean | null> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            return Promise.resolve(response.ok);
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<null>(<any>null);
    }
}

export interface TaskGroupViewModel {
    id: number;
    name: string;
    taskCount: number;
}

export interface TaskGroupDTO {
    name?: string | undefined;
}

export interface UserViewModel {
    id: number;
    fullName: string;
}

export interface UserTaskViewModel {
    id: number;
    name?: string | undefined;
    deadline: string;
    userId?: number | undefined;
    status: string;
    groupId: number;
}

export interface UserTaskDTO {
    name?: string | undefined;
    deadline?: string | undefined;
    userId?: number;
    status?: number;
    groupId: number;
}

export enum TaskStatus {
    New = 0,
    InProgress = 1,
    Completed = 2,
}

export class ApiException extends Error {
    message: string;
    status: number; 
    response: string; 
    headers: { [key: string]: any; };
    result: any; 

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}